package main

import "testing"

func TestParseBLSEntry(t *testing.T) {
	cases := []struct {
		name       string
		body       string
		wantLinux  string
		wantInitrd string
	}{
		{
			name:       "well-formed entry",
			body:       "title bazzite\nlinux /EFI/bazzite/vmlinuz\ninitrd /EFI/bazzite/initrd.img\noptions root=LABEL=TBOX_STORE\n",
			wantLinux:  "/EFI/bazzite/vmlinuz",
			wantInitrd: "/EFI/bazzite/initrd.img",
		},
		{
			name:       "extra whitespace + tabs",
			body:       "title  Bazzite Live\nlinux\t/images/pxeboot/bazzite/vmlinuz\ninitrd  /images/pxeboot/bazzite/initrd.img\n",
			wantLinux:  "/images/pxeboot/bazzite/vmlinuz",
			wantInitrd: "/images/pxeboot/bazzite/initrd.img",
		},
		{
			name:       "missing linux line",
			body:       "title x\ninitrd /a\n",
			wantLinux:  "",
			wantInitrd: "/a",
		},
		{
			name:       "blank lines and comments are tolerated",
			body:       "\n# generated by tacklebox\n\nlinux /vmlinuz\ninitrd /initrd.img\n\n",
			wantLinux:  "/vmlinuz",
			wantInitrd: "/initrd.img",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := parseBLSEntry(tc.body)
			if got.linux != tc.wantLinux {
				t.Errorf("linux = %q, want %q", got.linux, tc.wantLinux)
			}
			if got.initrd != tc.wantInitrd {
				t.Errorf("initrd = %q, want %q", got.initrd, tc.wantInitrd)
			}
		})
	}
}

func TestCheckBLSResolves(t *testing.T) {
	files := map[string]bool{
		"EFI/bazzite/vmlinuz":    true,
		"EFI/bazzite/initrd.img": true,
		"loader/loader.conf":     true,
	}
	cases := []struct {
		name    string
		entry   blsEntry
		wantErr bool
	}{
		{
			name:    "both resolve",
			entry:   blsEntry{name: "ok.conf", linux: "/EFI/bazzite/vmlinuz", initrd: "/EFI/bazzite/initrd.img"},
			wantErr: false,
		},
		{
			name:    "linux missing",
			entry:   blsEntry{name: "bad.conf", linux: "/EFI/aurora/vmlinuz", initrd: "/EFI/bazzite/initrd.img"},
			wantErr: true,
		},
		{
			name:    "initrd missing",
			entry:   blsEntry{name: "bad.conf", linux: "/EFI/bazzite/vmlinuz", initrd: "/EFI/aurora/initrd.img"},
			wantErr: true,
		},
		{
			name:    "both empty",
			entry:   blsEntry{name: "empty.conf"},
			wantErr: true,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			r := checkBLSResolves(tc.entry, files, "ESP")
			if (r.err != nil) != tc.wantErr {
				t.Errorf("got err=%v, wantErr=%v", r.err, tc.wantErr)
			}
		})
	}
}

func TestBLSOption(t *testing.T) {
	opts := "root=live:CDLABEL=X rd.live.squashimg=combined.rootfs.sfs tacklebox.root=bluefin"
	if got := blsOption(opts, "rd.live.squashimg"); got != "combined.rootfs.sfs" {
		t.Errorf("squashimg = %q", got)
	}
	if got := blsOption(opts, "tacklebox.root"); got != "bluefin" {
		t.Errorf("tacklebox.root = %q", got)
	}
	// Prefix must not match a longer key (tacklebox.root vs tacklebox.rootflags).
	if got := blsOption("tacklebox.rootflags=x", "tacklebox.root"); got != "" {
		t.Errorf("prefix collision: got %q, want empty", got)
	}
}

func TestBLSSquashimg(t *testing.T) {
	// Current spelling (tbox-live module).
	if got := blsSquashimg("root=tbox:CDLABEL=X tacklebox.live.squashimg=alpha.rootfs.sfs"); got != "alpha.rootfs.sfs" {
		t.Errorf("tbox-live spelling = %q", got)
	}
	// Legacy dmsquash-live spelling: ISOs built before the tbox-live
	// switch must stay verifiable.
	if got := blsSquashimg("root=live:CDLABEL=X rd.live.squashimg=beta.rootfs.sfs"); got != "beta.rootfs.sfs" {
		t.Errorf("legacy spelling = %q", got)
	}
	if got := blsSquashimg("root=LABEL=TBOX_STORE rw"); got != "" {
		t.Errorf("non-live entry = %q, want empty", got)
	}
}

func TestCheckCombinedPivots(t *testing.T) {
	combined := func(name, root string) blsEntry {
		return blsEntry{name: name, options: "tacklebox.live.squashimg=combined.rootfs.sfs tacklebox.root=" + root}
	}

	// Healthy combined layout: distinct pivots, one OK result.
	rs := checkCombinedPivots([]blsEntry{combined("a.conf", "bluefin"), combined("b.conf", "bazzite")})
	if len(rs) != 1 || rs[0].err != nil {
		t.Errorf("healthy combined: got %+v", rs)
	}

	// Shared pivot = collision.
	rs = checkCombinedPivots([]blsEntry{combined("a.conf", "bluefin"), combined("b.conf", "bluefin")})
	if len(rs) == 0 || rs[len(rs)-1].err == nil {
		t.Errorf("shared pivot should fail: %+v", rs)
	}

	// Missing pivot arg on one entry.
	rs = checkCombinedPivots([]blsEntry{
		combined("a.conf", "bluefin"),
		{name: "b.conf", options: "rd.live.squashimg=combined.rootfs.sfs"},
	})
	var failed bool
	for _, r := range rs {
		if r.err != nil {
			failed = true
		}
	}
	if !failed {
		t.Errorf("missing tacklebox.root should fail: %+v", rs)
	}

	// Per-env layout (distinct squashimgs): not combined, no results.
	perEnv := []blsEntry{
		{name: "a.conf", options: "rd.live.squashimg=bluefin.rootfs.sfs"},
		{name: "b.conf", options: "rd.live.squashimg=bazzite.rootfs.sfs"},
	}
	if rs := checkCombinedPivots(perEnv); rs != nil {
		t.Errorf("per-env layout should be skipped: %+v", rs)
	}
}

func TestCheckCombinedPivotsDeltaLayout(t *testing.T) {
	deltaEnv := func(name, delta string) blsEntry {
		opts := "tacklebox.live.squashimg=base.rootfs.sfs"
		if delta != "" {
			opts += " tacklebox.live.delta=" + delta
		}
		return blsEntry{name: name, options: opts}
	}

	// Healthy delta layout: one bare base entry + distinct deltas.
	rs := checkCombinedPivots([]blsEntry{
		deltaEnv("base.conf", ""),
		deltaEnv("a.conf", "a.delta.sfs"),
		deltaEnv("b.conf", "b.delta.sfs"),
	})
	if len(rs) != 1 || rs[0].err != nil {
		t.Errorf("healthy delta layout: got %+v", rs)
	}

	// Two entries sharing one delta boot identical content.
	rs = checkCombinedPivots([]blsEntry{
		deltaEnv("base.conf", ""),
		deltaEnv("a.conf", "same.delta.sfs"),
		deltaEnv("b.conf", "same.delta.sfs"),
	})
	if !anyFailed(rs) {
		t.Errorf("shared delta should fail: %+v", rs)
	}

	// Two bare entries: only the base env may boot the base as-is.
	rs = checkCombinedPivots([]blsEntry{
		deltaEnv("base.conf", ""),
		deltaEnv("other.conf", ""),
		deltaEnv("a.conf", "a.delta.sfs"),
	})
	if !anyFailed(rs) {
		t.Errorf("two bare entries should fail: %+v", rs)
	}
}

func anyFailed(rs []checkResult) bool {
	for _, r := range rs {
		if r.err != nil {
			return true
		}
	}
	return false
}
