package purefs

import (
	"strings"

	"github.com/tuna-os/tacklebox/internal/oci"
)

// DetectDesktop mirrors the live baseline's desktop detection against an
// unpacked image tree: the browser builder uses it to auto-configure the
// live setup (autologin adapter, installer app, flatpak defaults) from
// an arbitrary bootable image, before any authoring happens.
func DetectDesktop(root *oci.Node) string {
	has := func(p string) bool { return root.Lookup(p) != nil }
	switch {
	case has("usr/share/wayland-sessions/plasma.desktop"),
		has("usr/share/wayland-sessions/plasmawayland.desktop"):
		return "kde"
	case has("usr/share/wayland-sessions/niri.desktop"):
		return "niri"
	case has("usr/share/wayland-sessions/cosmic.desktop"):
		return "cosmic"
	}
	for _, dir := range []string{"usr/share/xsessions", "usr/share/wayland-sessions"} {
		if d := root.Lookup(dir); d != nil {
			for name := range d.Children {
				if len(name) >= 4 && name[:4] == "xfce" {
					return "xfce"
				}
			}
		}
	}
	if has("usr/share/wayland-sessions") || has("usr/share/xsessions") {
		return "gnome"
	}
	return "none"
}

// DetectPackaging returns (package manager, repology repo-family prefix)
// from the image tree — the browser builder uses it to route package
// search to the right ecosystem and to emit a correct remora manifest.
func DetectPackaging(root *oci.Node) (pm, family string) {
	has := func(p string) bool { return root.Lookup(p) != nil }
	switch {
	case has("usr/bin/dnf"), has("usr/bin/dnf5"), has("usr/bin/rpm-ostree"):
		// Distinguish Fedora vs EL by os-release later; default fedora.
		return "dnf", "fedora"
	case has("usr/bin/zypper"):
		return "zypper", "opensuse"
	case has("usr/bin/pacman"):
		return "pacman", "arch"
	case has("usr/bin/apt"), has("usr/bin/apt-get"):
		return "apt", "debian"
	case has("usr/bin/emerge"):
		return "emerge", "gentoo"
	case has("sbin/apk"), has("usr/bin/apk"):
		return "apk", "alpine"
	}
	return "", ""
}

// ImageFacts is what the builder GUI shows after introspection.
type ImageFacts struct {
	Desktop   string `json:"desktop"`
	KernelVer string `json:"kernelVer"`
	HasSdBoot bool   `json:"hasSdBoot"`
	// Bootloader is the resolved live-ISO boot chain: "systemd-boot",
	// "grub2" (bootupd shim+GRUB pair), or "none" when the image ships
	// neither (see DetectBootChain).
	Bootloader string `json:"bootloader"`
	FileCount  int    `json:"fileCount"`
	PkgManager string `json:"pkgManager"`
	RepoFamily string `json:"repoFamily"`
	// SuggestedFlatpaks is the image's own flatpak preinstall.d set
	// (see PreinstallRefs), so the builder can show what the live
	// session is expected to carry.
	SuggestedFlatpaks []string `json:"suggestedFlatpaks"`
}

func Introspect(root *oci.Node, store oci.BlobStore) ImageFacts {
	facts := ImageFacts{Desktop: DetectDesktop(root)}
	if mods := root.Lookup("usr/lib/modules"); mods != nil {
		for name := range mods.Children {
			if mods.Lookup(name+"/vmlinuz") != nil {
				facts.KernelVer = name
				break
			}
		}
	}
	facts.HasSdBoot = root.Lookup("usr/lib/systemd/boot/efi/systemd-bootx64.efi") != nil
	facts.Bootloader = "none"
	if bc, err := DetectBootChain(root); err == nil {
		if bc.Kind == "sdboot" {
			facts.Bootloader = "systemd-boot"
		} else {
			facts.Bootloader = "grub2"
		}
	}
	facts.PkgManager, facts.RepoFamily = DetectPackaging(root)
	facts.SuggestedFlatpaks = SuggestedFlatpaks(root, store)
	root.Walk(func(_ string, n *oci.Node) error {
		if n.Type == oci.TypeFile {
			facts.FileCount++
		}
		return nil
	})
	return facts
}

// RemoraManifest renders a remora.yaml (tacklebox#99) from the builder's
// package + extra_run inputs. Kept trivial and dependency-free so it
// compiles into the WASM bundle.
func RemoraManifest(pkgManager string, packages, extraRun []string) string {
	var b strings.Builder
	b.WriteString("# Generated by the TunaOS ISO Builder — https://iso.tunaos.org\n")
	b.WriteString("# remora rebuilds these layers on the upstream base and bootc-switches;\n")
	b.WriteString("# they persist across updates. Edit /etc/remora/remora.yaml to change.\n")
	if pkgManager != "" {
		b.WriteString("package_manager: " + pkgManager + "\n")
	}
	b.WriteString("packages:\n")
	for _, p := range packages {
		b.WriteString("  - " + p + "\n")
	}
	if len(extraRun) > 0 {
		b.WriteString("extra_run:\n")
		for _, r := range extraRun {
			// single-quote and escape embedded quotes for YAML safety
			b.WriteString("  - '" + strings.ReplaceAll(r, "'", "''") + "'\n")
		}
	}
	return b.String()
}
